name: Run Jenkins CI

on: push

jobs:
  jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Install Jenkins
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk
          wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
          sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
          sudo apt update
          sudo apt install -y jenkins
          sudo systemctl start jenkins
          echo "Jenkins is now running"
